### ISSUE TITLE
[Feature request] Apply "site:reddit.com" to the search box, instead of the currently displayed Google querry

### ISSUE THREAD

**Issue by fabiorzfreitas** [tadwohlrapp/reddit-search-on-google#3]
Hi,

I love your extension, I already liked marioortizmanero's userscript, but this is even better!

I don't know if this would be easy to implement or not, but the extension currently works like this:

1. Access google.com;
2. Type your query;
3. Click the search button;
4. Click the little icon to add "site:reddit.com"

I was wondering if it would be possible to skip step 3. Of course I'm only Google.com when I'm trying my first query, which I search from the browser's URL bar, as everyone does, but I often try a few queries before falling to reddit. In these situations, it would be useful to skip step 3.

BTW, it just something just occurred to me now! Perhaps the extension could place a small reddit button in the URL bar as well, and also made assignable to a keyboard shortcut. This would be quite an improvement, although I don't have a clue if it's feasible to even spend time developing it...

Anyway, thanks for the great extension!

**Comment by tadwohlrapp** [comment]
Hey there, sorry for taking my time to respond.

You're asking if it would be possible to add the "search on reddit" button, which is currently appended to the search input field on google.com, directly to the browser's address bar?
If so, sorry to disappoint but currently I don't plan to add any functionality to the browser itself.

But in most browsers you can already add customized search engines!

**In Chrome:**
1. Open [chrome://settings/searchEngines](chrome://settings/searchEngines)
2. Scroll down to "Site search" and click "Add"
3. Enter the following:
<img width="542" alt="image" src="https://github.com/tadwohlrapp/reddit-search-on-google/assets/2788192/1874cb35-3a9e-4d9e-8a60-5039782dd537">

> Search engine: Reddit Search on Google
> Shortcut: rsog
> URL with %s in place of query: https://www.google.com/search?q=%s+site%3Areddit.com

Now you can just type `rsog something` into the address bar to open https://www.google.com/search?q=something+site%3Areddit.com

You could even shorten it to just `r` instead of `rsog`.

**In Firefox** it seems to be a bit more complicated to add custom search engines. See https://www.reddit.com/r/firefox/comments/ob8ffw/comment/h3mcfh7/

**Comment by fabiorzfreitas** [comment]
For future reference, it's [easy on Firefox as well](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox).

Reddit itself isn't available as an engine, so I used Mozilla's suggestion for the [**Mycroft Project**](https://mycroftproject.com/).

There are [dozens of plugins for reddit related search engines](https://mycroftproject.com/search-engines.html?name=reddit), sometimes with different search parameters (like a plugin for an engine specific to a subreddit), I chose [this one](https://mycroftproject.com/install.html?id=91876&basename=google_on_reddit&icontype=png&name=Reddit+-+Google).

Also, I glanced at their developer section, and I think these custom search engine plugins are very straightforward to create...

Perhaps if new feature requests are also out of the addon's scope, this could be a place to point users to!

**Comment by tadwohlrapp** [comment]
Oh, that's good to know. Thanks for the resources!
